/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    readonly "/agents": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** List Agents */
        readonly get: operations["list_agents_agents_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/agents/{slug}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get Agent */
        readonly get: operations["get_agent_agents__slug__get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/agents/{slug}/signals": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get Agent Signals */
        readonly get: operations["get_agent_signals_agents__slug__signals_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/agents/{slug}/benchmarks": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get Agent Benchmarks */
        readonly get: operations["get_agent_benchmarks_agents__slug__benchmarks_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/agents/{slug}/similar": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get Similar Agents */
        readonly get: operations["get_similar_agents_agents__slug__similar_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/indexes": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** List Indexes */
        readonly get: operations["list_indexes_indexes_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/indexes/{slug}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get Index */
        readonly get: operations["get_index_indexes__slug__get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/indexes/{slug}/history": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get Index History */
        readonly get: operations["get_index_history_indexes__slug__history_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/indexes/{slug}/rebalances": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get Index Rebalances */
        readonly get: operations["get_index_rebalances_indexes__slug__rebalances_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/movers": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get Movers */
        readonly get: operations["get_movers_movers_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/search": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Search */
        readonly get: operations["search_search_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/tags": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** List Tags */
        readonly get: operations["list_tags_tags_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/events": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** List Events */
        readonly get: operations["list_events_events_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/discovery/recent": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Recent Admissions */
        readonly get: operations["recent_admissions_discovery_recent_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Root */
        readonly get: operations["root__get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/health": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe — the process is alive. Always returns 200 if reachable.
         */
        readonly get: operations["health_health_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/ready": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Ready
         * @description Readiness — Postgres + Redis pings. Returns 503 with detail if either fails.
         */
        readonly get: operations["ready_ready_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentDetail
         * @description The full /agents/:slug payload.
         */
        readonly AgentDetail: {
            /**
             * Id
             * Format: uuid
             */
            readonly id: string;
            /** Slug */
            readonly slug: string;
            /** Name */
            readonly name: string;
            /** Description */
            readonly description: string | null;
            /** Discovered Via */
            readonly discovered_via: string;
            /**
             * Discovered At
             * Format: date-time
             */
            readonly discovered_at: string;
            /** Homepage Url */
            readonly homepage_url: string | null;
            /** Github Repo */
            readonly github_repo: string | null;
            readonly score: components["schemas"]["ScoreEnvelopeOptional"];
            /** Hf Org */
            readonly hf_org: string | null;
            /** Hf Model Ids */
            readonly hf_model_ids: readonly string[] | null;
            /** Package Names */
            readonly package_names: {
                readonly [key: string]: unknown;
            } | null;
            /** Arxiv Ids */
            readonly arxiv_ids: readonly string[] | null;
            /** Eligibility Status */
            readonly eligibility_status: string;
            /** Eligibility Score */
            readonly eligibility_score: number | null;
            /** Eligibility Reasons */
            readonly eligibility_reasons: {
                readonly [key: string]: unknown;
            } | null;
            /** Manipulation Flags */
            readonly manipulation_flags: {
                readonly [key: string]: unknown;
            } | null;
            /** Tags */
            readonly tags: readonly components["schemas"]["TagOut"][];
        };
        /**
         * AgentSummary
         * @description The compact form returned in /agents and /movers.
         */
        readonly AgentSummary: {
            /**
             * Id
             * Format: uuid
             */
            readonly id: string;
            /** Slug */
            readonly slug: string;
            /** Name */
            readonly name: string;
            /** Description */
            readonly description: string | null;
            /** Discovered Via */
            readonly discovered_via: string;
            /**
             * Discovered At
             * Format: date-time
             */
            readonly discovered_at: string;
            /** Homepage Url */
            readonly homepage_url: string | null;
            /** Github Repo */
            readonly github_repo: string | null;
            readonly score: components["schemas"]["ScoreEnvelopeOptional"];
        };
        /** BenchmarkResultOut */
        readonly BenchmarkResultOut: {
            /**
             * Benchmark Id
             * Format: uuid
             */
            readonly benchmark_id: string;
            /** Benchmark Name */
            readonly benchmark_name: string;
            /**
             * Captured At
             * Format: date-time
             */
            readonly captured_at: string;
            /** Score */
            readonly score: number;
            /** Max Score */
            readonly max_score: number | null;
        };
        /** EventOut */
        readonly EventOut: {
            /**
             * Id
             * Format: uuid
             */
            readonly id: string;
            /** Kind */
            readonly kind: string;
            /** Agent Id */
            readonly agent_id: string | null;
            /** Payload */
            readonly payload: {
                readonly [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            readonly created_at: string;
        };
        /** FacetCount */
        readonly FacetCount: {
            /** Value */
            readonly value: string;
            /** Count */
            readonly count: number;
        };
        /** HTTPValidationError */
        readonly HTTPValidationError: {
            /** Detail */
            readonly detail?: readonly components["schemas"]["ValidationError"][];
        };
        /** IndexConstituent */
        readonly IndexConstituent: {
            readonly agent: components["schemas"]["AgentSummary"];
            /** Weight */
            readonly weight: number;
            /**
             * Added At
             * Format: date-time
             */
            readonly added_at: string;
        };
        /** IndexDetail */
        readonly IndexDetail: {
            /**
             * Id
             * Format: uuid
             */
            readonly id: string;
            /** Slug */
            readonly slug: string;
            /** Name */
            readonly name: string;
            /** Methodology Md */
            readonly methodology_md: string | null;
            /** Rebalance Frequency */
            readonly rebalance_frequency: string;
            /** Members Count */
            readonly members_count: number;
            /** Composite Value */
            readonly composite_value: number | null;
            /** Constituents */
            readonly constituents: readonly components["schemas"]["IndexConstituent"][];
            /** Last Rebalance At */
            readonly last_rebalance_at: string | null;
        };
        /** IndexSnapshotOut */
        readonly IndexSnapshotOut: {
            /**
             * Captured At
             * Format: date-time
             */
            readonly captured_at: string;
            /** Composite Value */
            readonly composite_value: number;
        };
        /** IndexSummary */
        readonly IndexSummary: {
            /**
             * Id
             * Format: uuid
             */
            readonly id: string;
            /** Slug */
            readonly slug: string;
            /** Name */
            readonly name: string;
            /** Methodology Md */
            readonly methodology_md: string | null;
            /** Rebalance Frequency */
            readonly rebalance_frequency: string;
            /** Members Count */
            readonly members_count: number;
            /** Composite Value */
            readonly composite_value: number | null;
        };
        /** MoverOut */
        readonly MoverOut: {
            readonly agent: components["schemas"]["AgentSummary"];
            /**
             * Delta
             * @description agent_score now minus agent_score at window-start
             */
            readonly delta: number;
            /** Score At Window Start */
            readonly score_at_window_start: number | null;
            /** Score Now */
            readonly score_now: number;
        };
        /** Page[AgentSummary] */
        readonly Page_AgentSummary_: {
            /** Items */
            readonly items: readonly components["schemas"]["AgentSummary"][];
            /** Total */
            readonly total: number;
            /** Limit */
            readonly limit: number;
            /** Offset */
            readonly offset: number;
        };
        /** Page[EventOut] */
        readonly Page_EventOut_: {
            /** Items */
            readonly items: readonly components["schemas"]["EventOut"][];
            /** Total */
            readonly total: number;
            /** Limit */
            readonly limit: number;
            /** Offset */
            readonly offset: number;
        };
        /** RebalanceOut */
        readonly RebalanceOut: {
            /**
             * Id
             * Format: uuid
             */
            readonly id: string;
            /**
             * Run At
             * Format: date-time
             */
            readonly run_at: string;
            /** Additions */
            readonly additions: readonly {
                readonly [key: string]: unknown;
            }[] | null;
            /** Removals */
            readonly removals: readonly {
                readonly [key: string]: unknown;
            }[] | null;
            /** Weight Changes */
            readonly weight_changes: readonly {
                readonly [key: string]: unknown;
            }[] | null;
            /** Narrative Md */
            readonly narrative_md: string | null;
        };
        /**
         * ScoreEnvelopeOptional
         * @description Score envelope variant for endpoints where an agent may have no score yet.
         */
        readonly ScoreEnvelopeOptional: {
            /** Agent Score */
            readonly agent_score?: number | null;
            /** Adoption */
            readonly adoption?: number | null;
            /** Quality */
            readonly quality?: number | null;
            /** Momentum */
            readonly momentum?: number | null;
            /** Community */
            readonly community?: number | null;
            /** Manipulation Resistance */
            readonly manipulation_resistance?: number | null;
            /** Computed At */
            readonly computed_at?: string | null;
        };
        /** SearchHit */
        readonly SearchHit: {
            readonly agent: components["schemas"]["AgentSummary"];
            /** Similarity */
            readonly similarity?: number | null;
        };
        /** SearchResult */
        readonly SearchResult: {
            /** Hits */
            readonly hits: readonly components["schemas"]["SearchHit"][];
            /** Facets */
            readonly facets: {
                readonly [key: string]: readonly components["schemas"]["FacetCount"][];
            };
        };
        /** SignalPoint */
        readonly SignalPoint: {
            /**
             * Captured At
             * Format: date-time
             */
            readonly captured_at: string;
            /** Value */
            readonly value: number;
        };
        /** SignalSeries */
        readonly SignalSeries: {
            /** Source */
            readonly source: string;
            /** Points */
            readonly points: readonly components["schemas"]["SignalPoint"][];
        };
        /** SimilarAgent */
        readonly SimilarAgent: {
            readonly agent: components["schemas"]["AgentSummary"];
            /** Similarity */
            readonly similarity: number;
        };
        /** TagOut */
        readonly TagOut: {
            /** Kind */
            readonly kind: string;
            /** Value */
            readonly value: string;
            /** Display Name */
            readonly display_name: string;
        };
        /** TagWithCount */
        readonly TagWithCount: {
            /** Kind */
            readonly kind: string;
            /** Value */
            readonly value: string;
            /** Display Name */
            readonly display_name: string;
            /** Count */
            readonly count: number;
        };
        /** ValidationError */
        readonly ValidationError: {
            /** Location */
            readonly loc: readonly (string | number)[];
            /** Message */
            readonly msg: string;
            /** Error Type */
            readonly type: string;
            /** Input */
            readonly input?: unknown;
            /** Context */
            readonly ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readonly list_agents_agents_get: {
        readonly parameters: {
            readonly query?: {
                /** @description Substring match on slug/name/description */
                readonly q?: string | null;
                /** @description Filter by tag kind (capability/domain/...) */
                readonly tag_kind?: string | null;
                /** @description Filter by tag value */
                readonly tag_value?: string | null;
                readonly sort?: string;
                readonly limit?: number;
                readonly offset?: number;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Page_AgentSummary_"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_agent_agents__slug__get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly slug: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["AgentDetail"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_agent_signals_agents__slug__signals_get: {
        readonly parameters: {
            readonly query?: {
                /** @description Filter by signal_source values */
                readonly sources?: readonly string[] | null;
                readonly window?: string;
                readonly limit?: number;
            };
            readonly header?: never;
            readonly path: {
                readonly slug: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["SignalSeries"][];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_agent_benchmarks_agents__slug__benchmarks_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly slug: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["BenchmarkResultOut"][];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_similar_agents_agents__slug__similar_get: {
        readonly parameters: {
            readonly query?: {
                readonly limit?: number;
            };
            readonly header?: never;
            readonly path: {
                readonly slug: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["SimilarAgent"][];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly list_indexes_indexes_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["IndexSummary"][];
                };
            };
        };
    };
    readonly get_index_indexes__slug__get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly slug: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["IndexDetail"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_index_history_indexes__slug__history_get: {
        readonly parameters: {
            readonly query?: {
                readonly window?: string;
                readonly limit?: number;
            };
            readonly header?: never;
            readonly path: {
                readonly slug: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["IndexSnapshotOut"][];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_index_rebalances_indexes__slug__rebalances_get: {
        readonly parameters: {
            readonly query?: {
                readonly limit?: number;
            };
            readonly header?: never;
            readonly path: {
                readonly slug: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["RebalanceOut"][];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_movers_movers_get: {
        readonly parameters: {
            readonly query?: {
                readonly window?: string;
                readonly limit?: number;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["MoverOut"][];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly search_search_get: {
        readonly parameters: {
            readonly query: {
                readonly q: string;
                readonly mode?: string;
                readonly limit?: number;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["SearchResult"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly list_tags_tags_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["TagWithCount"][];
                };
            };
        };
    };
    readonly list_events_events_get: {
        readonly parameters: {
            readonly query?: {
                /** @description Filter by event kind: agent_admitted, score_changed, rank_changed, index_rebalanced, signal_spike, agent_flagged */
                readonly kind?: string | null;
                readonly limit?: number;
                readonly offset?: number;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Page_EventOut_"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly recent_admissions_discovery_recent_get: {
        readonly parameters: {
            readonly query?: {
                readonly limit?: number;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["AgentSummary"][];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly root__get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly [key: string]: string;
                    };
                };
            };
        };
    };
    readonly health_health_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly [key: string]: string;
                    };
                };
            };
        };
    };
    readonly ready_ready_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly [key: string]: unknown;
                    };
                };
            };
        };
    };
}
