// AgentTape shared types.
//
// The OpenAPI-derived types live in `./api` (auto-generated by
// openapi-typescript from apps/api/openapi.json — do NOT edit `api.ts`
// by hand). Run `pnpm --filter @agenttape/shared generate:types` after
// any API schema change.
//
// We also export a small set of hand-curated types here for things the
// REST API doesn't model directly (realtime frames, ingestion tier
// names, etc.).

export type * from "./api.js";

// Realtime frame envelope. The realtime service sends one of these on
// every WebSocket / SSE message.
export type RealtimeFrame =
  | RealtimeSnapshot
  | RealtimeEvent
  | RealtimeHeartbeat
  | RealtimeWarning;

export interface RealtimeSnapshot {
  type: "snapshot";
  scope: "ticker" | "agent" | "index" | "watchlist";
  // Scope-specific payload — see apps/realtime/src/realtime/snapshots.py.
  [key: string]: unknown;
}

export interface RealtimeEvent {
  type: "event";
  channel: string;
  event: {
    kind: string;
    agent_id?: string;
    agent_slug?: string;
    [key: string]: unknown;
  };
}

export interface RealtimeHeartbeat {
  type: "heartbeat";
}

export interface RealtimeWarning {
  type: "warning";
  reason: "slow_client";
  detail: string;
}

export type IngestionTier = "fast" | "medium" | "slow";
