import Link from "next/link";

// Global footer. Lives on every page. Carries the discoverability
// links that don't earn a slot in the desktop nav, plus the
// not-financial-advice disclaimer that the trading metaphor demands.
//
// Mobile layout is 2-col (Product on left, Reading + Build stacked
// on the right) under a full-width brand blurb. Desktop is the
// flat 4-col grid you'd expect. The `md:contents` trick on the
// inner wrappers lets us keep one DOM and fan it out into the
// parent grid on desktop.

interface FooterColumn {
  title: string;
  items: { href: string; label: string }[];
}

const PRODUCT: FooterColumn = {
  title: "Product",
  items: [
    { href: "/", label: "Floor" },
    { href: "/sectors", label: "Sectors" },
    { href: "/indexes", label: "Indexes" },
    { href: "/models", label: "Models" },
    { href: "/trending", label: "Trending" },
    { href: "/new", label: "New" },
    { href: "/compare", label: "Compare" },
  ],
};

const READING: FooterColumn = {
  title: "Reading",
  items: [
    { href: "/articles", label: "Articles" },
    { href: "/methodology", label: "Methodology" },
    { href: "/about", label: "About" },
  ],
};

const BUILD: FooterColumn = {
  title: "Build",
  items: [
    // OpenAPI docs are auto-generated by FastAPI at the API host —
    // every endpoint with full request/response schema, no curated
    // /developers page to drift out of date.
    {
      href:
        (process.env.NEXT_PUBLIC_API_URL ?? "https://agenttape.com/api") +
        "/docs",
      label: "API · OpenAPI",
    },
    { href: "/rss/trending.xml", label: "RSS · Trending" },
    { href: "/sitemap.xml", label: "Sitemap" },
    {
      href: "https://github.com/flmwilkinson/AgentTape",
      label: "GitHub",
    },
  ],
};

function ColumnBlock({ col }: { col: FooterColumn }) {
  return (
    <div>
      <div className="mb-2 font-mono text-[10px] uppercase tracking-[0.2em] text-muted-foreground">
        {col.title}
      </div>
      <ul className="space-y-1 text-xs">
        {col.items.map((it) => (
          <li key={it.href}>
            {it.href.startsWith("http") ? (
              <a
                href={it.href}
                target="_blank"
                rel="noreferrer"
                className="text-foreground/80 hover:text-foreground"
              >
                {it.label}
              </a>
            ) : (
              <Link
                href={it.href}
                className="text-foreground/80 hover:text-foreground"
              >
                {it.label}
              </Link>
            )}
          </li>
        ))}
      </ul>
    </div>
  );
}

export function SiteFooter() {
  return (
    // pb-24 on mobile leaves clearance above the fixed bottom nav
    // (h-16) so the disclaimer text isn't hidden behind it.
    <footer className="hairline mt-12 border-t border-border bg-card md:mt-16">
      <div className="container pt-10 pb-24 md:pb-10">
        <div className="grid gap-8 md:grid-cols-4">
          <div className="space-y-2">
            <div className="font-mono text-xs font-semibold uppercase tracking-[0.2em]">
              AgentTape
            </div>
            <p className="max-w-xs text-xs text-muted-foreground">
              Live ranking of AI agents and foundation models, updated
              hourly from public signals. No curated list. Every input
              published.
            </p>
          </div>

          {/* On mobile this is a 2-col grid: Product on the left,
              Reading + Build stacked on the right. On desktop
              md:contents flattens both wrappers so the columns live
              directly under the parent grid (3 more cols → 4 total). */}
          <div className="grid grid-cols-2 gap-8 md:contents">
            <ColumnBlock col={PRODUCT} />
            <div className="space-y-6 md:contents">
              <ColumnBlock col={READING} />
              <ColumnBlock col={BUILD} />
            </div>
          </div>
        </div>

        <div className="mt-8 border-t border-border pt-4 text-[11px] text-muted-foreground">
          AgentTape is informational. The trading metaphor is a
          presentation choice. Nothing here is financial advice, and
          AgentScore is not a price.
        </div>
      </div>
    </footer>
  );
}
