import Link from "next/link";

// Global footer. Lives on every page. Carries the discoverability
// links that don't earn a slot in the desktop nav, plus the
// not-financial-advice disclaimer that the trading metaphor demands.

const COLUMNS: { title: string; items: { href: string; label: string }[] }[] = [
  {
    title: "Product",
    items: [
      { href: "/", label: "Floor" },
      { href: "/sectors", label: "Sectors" },
      { href: "/indexes", label: "Indexes" },
      { href: "/models", label: "Models" },
      { href: "/trending", label: "Trending" },
      { href: "/compare", label: "Compare" },
    ],
  },
  {
    title: "Reading",
    items: [
      { href: "/articles", label: "Articles" },
      { href: "/methodology", label: "Methodology" },
      { href: "/about", label: "About" },
      { href: "/report/inaugural", label: "Inaugural report" },
    ],
  },
  {
    title: "Build",
    items: [
      // OpenAPI docs are auto-generated by FastAPI at the API host —
      // every endpoint with full request/response schema, no curated
      // /developers page to drift out of date.
      {
        href:
          (process.env.NEXT_PUBLIC_API_URL ?? "https://agenttape.io/api") +
          "/docs",
        label: "API · OpenAPI",
      },
      { href: "/rss/trending.xml", label: "RSS · Trending" },
      { href: "/sitemap.xml", label: "Sitemap" },
      {
        href: "https://github.com/flmwilkinson/AgentTape",
        label: "GitHub",
      },
    ],
  },
];

export function SiteFooter() {
  return (
    <footer className="hairline mt-12 border-t border-border bg-card md:mt-16">
      <div className="container py-10">
        <div className="grid gap-8 md:grid-cols-4">
          <div className="space-y-2">
            <div className="font-mono text-xs font-semibold uppercase tracking-[0.2em]">
              AgentTape
            </div>
            <p className="max-w-xs text-xs text-muted-foreground">
              Live ranking of AI agents and foundation models, updated
              hourly from public signals. No curated list, every input
              published.
            </p>
          </div>
          {COLUMNS.map((col) => (
            <div key={col.title}>
              <div className="mb-2 font-mono text-[10px] uppercase tracking-[0.2em] text-muted-foreground">
                {col.title}
              </div>
              <ul className="space-y-1 text-xs">
                {col.items.map((it) => (
                  <li key={it.href}>
                    {it.href.startsWith("http") ? (
                      <a
                        href={it.href}
                        target="_blank"
                        rel="noreferrer"
                        className="text-foreground/80 hover:text-foreground"
                      >
                        {it.label}
                      </a>
                    ) : (
                      <Link
                        href={it.href}
                        className="text-foreground/80 hover:text-foreground"
                      >
                        {it.label}
                      </Link>
                    )}
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
        <div className="mt-8 border-t border-border pt-4 text-[11px] text-muted-foreground">
          AgentTape is informational. The trading metaphor is a
          presentation choice — nothing here is financial or investment
          advice, and AgentScore is not a price.
        </div>
      </div>
    </footer>
  );
}
